# fly.toml app configuration file generated for embed-zwi89a on 2026-04-28T21:55:33Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'embed-zwi89a'
primary_region = 'iad'

[build]

[[services]]
  protocol = "tcp"
  internal_port = 3000

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
      port = 443
      handlers = ["tls", "http"] 
[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
